# For STAR alignment to genome
ref:
  sequence:       /varidata/research/projects/bbc/versioned_references/2023-10-06_11.13.48_v14/data/mm10_gencode_plus_ERCC92/sequence/mm10_gencode_plus_ERCC92.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2023-10-06_11.13.48_v14/data/mm10_gencode_plus_ERCC92/sequence/mm10_gencode_plus_ERCC92.fa.fai
  index:          /varidata/research/projects/bbc/versioned_references/2023-10-06_11.13.48_v14/data/mm10_gencode_plus_ERCC92/indexes/star
  annotation:     /varidata/research/projects/bbc/versioned_references/2023-10-06_11.13.48_v14/data/mm10_gencode_plus_ERCC92/annotation/mm10_gencode_plus_ERCC92.gtf

# For salmon transcript pseudo-alignment
salmon:
  index_id:       mm10_gencode_plus_ERCC92
  transcripts:    /varidata/research/projects/bbc/versioned_references/2023-10-06_11.13.48_v14/data/mm10_gencode/annotation/mm10_gencode.transcripts.fasta
  decoys:         /varidata/research/projects/bbc/versioned_references/2023-10-06_11.13.48_v14/data/mm10_gencode/sequence/mm10_gencode.fa
  spikeins:       /varidata/research/projects/bbc/versioned_references/2023-10-06_11.13.48_v14/bin/spikeins/sequence/ERCC92.fa # can omit if no spikeins used

# additional parameters for trimGalore after removal of UMIs

# For SMARTer Stranded Total RNA-Seq Kit v3, the 5' end of R2 hads 8 bp UMI and then 6 bp linker/adapter
# To disable, set to an empty string, "".
clip_r2: "--clip_R2 6" 


# Can choose to run cogentAP if data comes from a Takara kit
run_cogent_ap: True
cogent_ap_ref: "mm10ERCC92gene"
cogent_ap_tech: "Stranded_UMI" # "Stranded_UMI" is for SMARTer Stranded Total RNA-Seq Kit v3; have not tested on other Takara kits 


# OrgDB R package for covnerting gene names. Common choices are 'org.Mm.eg.db' for mouse and 'org.Hs.eg.db' for human.
orgdb: org.Mm.eg.db

modules:
  bedtools: bbc2/bedtools/bedtools-2.30.0
  cogent_ap: bbc2/CogentAP/CogentAP-2.0
  fastqc: bbc2/fastqc/fastqc-0.12.1
  fastq_screen: bbc2/fastq_screen/fastq_screen-0.14.0
  htseq: bbc2/htseq/htseq-2.0.4
  multiqc: bbc2/multiqc/multiqc-1.14
  pigz: bbc2/pigz/pigz-2.7
  R: bbc2/R/alt/R-4.2.1-setR_LIBS_USER
  salmon: bbc2/salmon/salmon-1.10.0  
  samtools: bbc2/samtools/samtools-1.17
  star: bbc2/STAR/STAR-2.7.10a
  trim_galore: bbc2/trim_galore/trim_galore-0.6.10
  umi_tools: bbc2/UMI-tools/UMI-tools-1.1.4
